version: '3'

services:
    reverseproxy:
        build:
            context: ./reverse-proxy
        container_name: slack-status-reverse-proxy
        ports:
            - 443:443
        volumes:
            - ./frontend/build:/var/www/app
        restart: always

    webapp:
        build:
            context: .
        container_name: slack-status-webapp
        ports:
            - 5000:80
        env_file:
            - .env
        restart: always
        volumes:
            - ./db:/app/db

networks: 
    default:
        external:
            name: "nat"
        