version: '3'

services:
    reverseproxy:
        build:
            context: .
        container_name: slack-status-reverse-proxy
        ports:
            - 443:443
        restart: always

networks: 
    default:
        external:
            name: "nat"
        